<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hgon_donation"
 *
 * Auto generated by Extension Builder 2018-08-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'HGON Donation',
    'description' => 'Donation extension of HGON',
    'category' => 'plugin',
    'author' => 'Maximilian Fäßler',
    'author_email' => 'maximilian@faesslerweb.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '8.7.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
            'hgon_template' => '8.7.0-8.7.99',
            'rkw_basics' => '8.7.0-8.7.99',
            'rkw_projects' => '7.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
